trigger:
- '*'

pool:
  vmImage: 'windows-latest'

steps:


- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: SonarQubePrepare@5
  inputs:
    SonarQube: 'azdevops-sonarqube'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'my-terraform-project'
    cliProjectName: 'azdev'
    cliSources: '$(System.DefaultWorkingDirectory)/Create Multiple Windows Machine On Multiple Environment'
- task: SonarQubeAnalyze@5
  inputs:
    jdkversion: 'JAVA_HOME_11_X64'
    

- task: SonarQubePublish@5
  inputs:
    pollingTimeoutSec: '300'

