trigger:
- main

stages:
- stage: PublishArtifacts
  jobs:
  - job: publishartifacts
    pool:
      vmImage: ubuntu-latest
    continueOnError: false
    steps:
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(System.DefaultWorkingDirectory)/Create Multiple Windows Machine On Multiple Environment'
        artifact: 'aztf-publishartifacts'
        publishLocation: 'pipeline'

- stage: DEV
  displayName: 'Create Windows VM on DEV Environment'
  dependsOn: PublishArtifacts
  jobs:
  - job: TerraformInstall
    pool:
      vmImage: ubuntu-latest
    environment: dev
    variables:
    - group: terraform-auto-provision-on-dev-environment
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Create Multiple Windows Machine On Multiple Environment'
        backendServiceArm: 'Free Trial(2)(ef31447a-a9ec-499e-b0ae-61e8edbfb86e)'
        backendAzureRmResourceGroupName: 'd9LABZ-RG1-01'
        backendAzureRmStorageAccountName: 'd9labzstorageaccount'
        backendAzureRmContainerName: 'd9labzterraformcontainer'
        backendAzureRmKey: 'azure-vm-creation-devenv.tfstate'
    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'validate'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Create Multiple Windows Machine On Multiple Environment'
    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Create Multiple Windows Machine On Multiple Environment'
        environmentServiceNameAzureRM: 'Free Trial(2)(ef31447a-a9ec-499e-b0ae-61e8edbfb86e)'
    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Create Multiple Windows Machine On Multiple Environment'
        environmentServiceNameAzureRM: 'Free Trial(2)(ef31447a-a9ec-499e-b0ae-61e8edbfb86e)'

- stage: PRD
  displayName: 'Create Windows VM on PRD Environment'
  dependsOn: 
  - PublishArtifacts
  - DEV
  jobs:
  - job: TerraformInstall
    pool:
      vmImage: ubuntu-latest
    environment: prd
    variables:
    - group: terraform-auto-provision-on-prd-environment
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Create Multiple Windows Machine On Multiple Environment'
        backendServiceArm: 'Free Trial(2)(ef31447a-a9ec-499e-b0ae-61e8edbfb86e)'
        backendAzureRmResourceGroupName: 'd9LABZ-RG1-01'
        backendAzureRmStorageAccountName: 'd9labzstorageaccount'
        backendAzureRmContainerName: 'd9labzterraformcontainer'
        backendAzureRmKey: 'azure-vm-creation-prdenv.tfstate'
    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'validate'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Create Multiple Windows Machine On Multiple Environment'
    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Create Multiple Windows Machine On Multiple Environment'
        environmentServiceNameAzureRM: 'Free Trial(2)(ef31447a-a9ec-499e-b0ae-61e8edbfb86e)'
    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Create Multiple Windows Machine On Multiple Environment'
        environmentServiceNameAzureRM: 'Free Trial(2)(ef31447a-a9ec-499e-b0ae-61e8edbfb86e)'
