trigger:
- '*'

pool:
  vmImage: 'windows-latest'

steps:


- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: SonarQubePrepare@5
  inputs:
    SonarQube: 'azdevops-sonarqube'
    scannerMode: 'CLI'
    configMode: 'file'
    configFile: '$(System.DefaultWorkingDirectory)/Create Multiple Windows Machine On Multiple Environment/sonar-project.properties'
    extraProperties: |
      # Additional properties that will be passed to the scanner, 
      # Put one key=value per line, example:
      # sonar.exclusions=**/*.bin
      
      $params = "$env:SONARQUBE_SCANNER_PARAMS" -replace '"sonar.branch.name":"[\w,/,-]*"\,?'
      Write-Host "##vso[task.setvariable variable=SONARQUBE_SCANNER_PARAMS]$params"
- task: SonarQubeAnalyze@5
  inputs:
    jdkversion: 'JAVA_HOME_11_X64'
    

- task: SonarQubePublish@5
  inputs:
    pollingTimeoutSec: '300'

